### ISSUE TITLE
Unicode value not found bug when using fix write defaults component with certain characters

### ISSUE THREAD

**Issue by SouljaVR** [VRCFury/VRCFury#243] opened 2024-02-05 07:45 UTC
When using the 'Fix Write Defaults' component, if any of the avatar controllers contain parameters with special characters it causes Unity to lag pretty badly and spams this error:

The character with Unicode value \u1B85 was not found in the [Inter-Regular SDF] font asset or any potential fallbacks. It was replaced by Unicode character \u25A1.
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

![image](https://github.com/VRCFury/VRCFury/assets/97592971/4e8265ad-2720-4532-92dd-e12c234a09e4)

I believe it is to do with the debug info panel not being able to display the characters correctly so it just sh*ts itself. Besides this though things work fine. Thanks for your work!

**Comment by SenkyDragon** [comment] 2024-02-05 14:30
If possible, please join the vrcfury discord at https://vrcfury.com/discord and provide a copy of the controller which causes this issue. The warnings aren't something that we have much control over, but I expect that the lag issue may instead be caused by an excessively complex state machine.

I'm going to close this until a reproduction is available, as in the current state, I don't think we really have any control over whether or not these warnings are displayed unless we just strip all non-ascii characters, which I think would be a disservice to any non-english controller creators.

**Closed by SenkyDragon** 2024-02-05 14:30 UTC
