### ISSUE TITLE
[Feature Request] Mood Toggles for gestures

### ISSUE THREAD

**Issue by jonchampagne** [VRCFury/VRCFury#192] opened 2023-12-09 18:47 UTC
This is a feature in combo-gesture-expressions-av3 that would be nice to have native support for in VRCFury. 
Essentially, you can have multiple sets of gestures and are able to toggle between them. For example, happy, sad, angry, sleepy, etc. A bit more details on how it works here. https://hai-vr.github.io/combo-gesture-expressions-av3/#using-multiple-mood-sets

I'm imagining in vrcfury it might work similarly to the exclusive tags, and then a simple toggle in the expressions menu. If you can think of a better way though, then by all means don't feel restricted by my suggestion.

**Comment by SenkyDragon** [comment] 2024-09-10 10:42
Duplicate of #99

**Closed by SenkyDragon** 2024-09-10 10:42 UTC
