### ISSUE TITLE
Unity now breaks cross-controller transforms when a wd off layer is unmasked, even if it doesn't animate transforms

### ISSUE THREAD

**Issue by Saberpeep** [VRCFury/VRCFury#155] opened 2023-11-05 21:21 UTC
Using VRCFury 1.506.0. The **Fix Write Defaults** component with mode set to **Disabled** acts as though it it still set to **Auto**.

This issue is somewhat related to #100 . Someone suggested using the **Fix Write Defaults** component to mitigate the issue there however it seems the **Disabled** mode doesn't actually disable this feature and the "Defaults" layer is still inserted at the top of animators.

The other fix modes appear to work as described.

**Comment by Saberpeep** [comment] 2023-11-05 21:31
Just noticed #39 . If this is by design then perhaps rather than a bug this should be a feature request. I see three possible solutions:
1. Use the Avatars3.0Manager syntax and look for `(WD On)` in animator state names and exclude those from WD fixes.
2. Check for direct blend trees and exclude those from WD fixes.
3. Add a version of the FixWriteDefaults component that is designed to be placed on the prefab/template that controls the WD fixing behavior for that item (rather than for the base avatar).

**Comment by SenkyDragon** [comment] 2023-11-06 13:23
> Check for direct blend trees and exclude those from WD fixes.

It already does this.

**Comment by SenkyDragon** [comment] 2023-11-06 13:24
If you are having an issue with a specific asset, feel free to request in the support discord at https://vrcfury.com/discord . I don't believe there is a bug being tracked in this issue.

**Comment by Saberpeep** [comment] 2023-11-06 19:29
Ok, try it for yourself then: I have assembled the minimal possible test case which reproduces the issue using only parts included with the SDK:
1. Create a new Avatars project in the VCC.
2. Add VRCFury 1.510.0 and open the project.
3. Import the test package and open the included scene ( [VRCFury Test Case.zip](https://github.com/VRCFury/VRCFury/files/13271680/VRCFury.Test.Case.zip) )
4. Enter play mode and navigate to the FX layer generated by VRCFury.

Observe that VRCFury added a `[VF32] Defaults` layer and if you inspect the animation clip `VF32 FixWriteDefaultsBuilder/Defaults` it added and you can clearly see that the keyframe in it came from the direct blend tree. 

![result](https://github.com/VRCFury/VRCFury/assets/3688260/437a09da-018d-4a51-ba63-61e157101773)

This demonstration file includes one FX animator with a single WD On toggle, and one FX animator with one Direct Blend Tree. VRCFury is asked to merge the one with the Direct Blend Tree into the one with WD Off. VRCFury correctly detects that the base avatar is WD-Off but incorrectly attempts to "fix" the Direct Blend Tree by adding the reset animation.

**Comment by SenkyDragon** [comment] 2023-11-06 21:58
Adding the reset animation is also expected, even when the source is a direct blend tree. This is important for layers where the direct tree is not the only state in the state machine. Is this causing an issue?

**Comment by Saberpeep** [comment] 2023-11-06 22:22
I've been working with VRCFT face tracking templates (in particular [the ones by Jerry](https://github.com/Adjerry91/VRCFaceTracking-Templates) ), and merging them into an avatar designed with WD-Off basically breaks all animations on the Gesture animator because of these extra layer(s) added by VRCFury in the FX animator. If I remove this added layer, or add an appropriate avatar mask to it, then the animations go back to working as intended. It's a niche thing because most people still use WD-On, or take the easy way out and just do everything on the FX animator, and thus don't run into this.

**Comment by SenkyDragon** [comment] 2023-11-06 22:24
Are there any transform animations in the defaults layer in this case? A mask shouldn't be required if there are no transforms.

**Comment by Saberpeep** [comment] 2023-11-06 22:30
No, but the first layer of the FX animator must be a mask that masks out the parts animated in the Gesture animator as in accordance with the [official docs](https://creators.vrchat.com/avatars/playable-layers/#fx):
> If you have non-muscle animations in your gestures (eg. your Gesture [mask](https://docs.unity3d.com/2019.4/Documentation/Manual/class-AvatarMask.html) has any transforms checked at the bottom) those same transforms must be DISABLED in your FX mask. This will allow your Gesture animations to "show through" the FX layer.

The VRCFury `Defaults` layer is inserted at the very top and replaces any existing topmost layer that would normally have this mask,

**Comment by SenkyDragon** [comment] 2023-11-06 22:37
VRCF accomplishes the same goal by masking every FX layer containing transform animations, rather than masking the base layer (which provides it with more flexible options). The base layer is not supposed to have a mask in this case, because the per-layer masks are present where needed. The base layer is then merged with the defaults layer (in this specific case) because the defaults layer does not have any additional masking requirements as it does not contain any transforms in your example.

**Comment by Saberpeep** [comment] 2023-11-06 23:14
Unfortunately the base layer (both in FX and Gesture and even Action) is a special significance for VRChat and the mask there is required. VRChat even automatically generates a mask for the FX animator's base layer at runtime if you don't specify one: 
> The mask in the first FX layer, by default is empty, this will (at avatar init) create a default mask that disables all humanoid muscles, but enables all GameObject animations. This means that any animations in the hierarchy should work, although it is still NOT RECOMMENDED to animate transforms here.

If you still don't believe me I have amended the example from before with a simple Gesture animator:
1. Import this new package over the example from before [VRCFury Test Case + Gesture.zip](https://github.com/VRCFury/VRCFury/files/13273413/VRCFury.Test.Case.%2B.Gesture.zip).
2. Add Av3Emulator via the VCC, enter play mode, and then enable the emulator from the tools menu.
3. Observe as the tail does not wag.
4. Leave play mode and remove the VRCFury script from the avatar.
5. Enter play Mode and enable the emulator again.
6. Observe as the tail wags as intended.

This new Gesture animator is a copy of the Hands animator that comes with the VRCSDK but with a simple non-humanoid animation added that wags the tail on loop. The tail layer has been masked properly, and the base mask on the Gesture animator has been updated to include the tail.

**Comment by SenkyDragon** [comment] 2023-11-07 00:10
Interestingly, this works fine with Gesture Manager, but is broken in game. I'll dive in a bit and reopen once I find the best path forward.

**Comment by SenkyDragon** [comment] 2023-11-07 02:36
Not sure when this changed, but even our previous WD off "transforms in gesture" test project is broken now. I'd blame the unity runtime upgrade, but it's very strange the the behavior is matched in the latest release of av3emu.

Revisiting your suggestion earlier about a base layer mask: Unfortunately, if ANY mask is present on a layer, it prevents any material swap from working in slots other that slot 0. There is no mask you can provide that allows material swaps in those higher slots. Thanks unity.

However, luckily the issue wasn't actually caused by the base layer missing a mask, but rather that it seems that the restrictions around which layers require transform masks have become more stringent. Even FX layers which do not affect transforms whatsoever now need a mask in order to not break those transforms that are animated in Gesture.

Give 1.511 a shot and see if it resolves your issue.

**Closed by SenkyDragon** 2023-11-07 02:36 UTC

**Comment by SenkyDragon** [comment] 2023-11-07 02:40
BTW, It's our official recommendation that ALL non-humanoid transform animation should be done in FX. However, we do provide best effort to maintain compatibility with avatars that don't follow that advice.

**Comment by Saberpeep** [comment] 2023-11-07 03:41
Just tested with 1.511 both in the test project and in my original project and it's looking good! Interesting that it wasn't actually the base layer, sorry for being so adamant about what ended up sort of a red herring. As for doing non-humanoid transforms on the Gesture animator I was following the advice on the official VRChat docs. Though they seem to have been updated since then to sort of agree with you, and sort of not, they contradict themselves in multiple places. I'm beginning to agree with your advice though.

Though of course having no mask on that first layer will break humanoid animations on the FX layer because of the default mask that VRChat assigns, though I suppose that's outside of spec anyways. (To fix that you'd probably have to have it generate a mask that is an additive combo of all masks on that animator after merging, to account for possible things that are getting merged in). That's up to you though if you want to support that, and I can definitely see how that might get annoying if it breaks some other obscure setup.

Thanks for the fix 👍
