### ISSUE TITLE
Cannot use an Int as a Multiplier paramater

### ISSUE THREAD

**Issue by RantiMess** [VRCFury/VRCFury#221] opened 2024-01-15 04:41 UTC
I was trying to use an int from a heartrate monitor as a multiplier for an animation on my FX layer, without fury it works fine in vrchat and in the editor, when using fury however it gets changed to InvalidParamFloat and breaks.
![image](https://github.com/VRCFury/VRCFury/assets/7977612/714e9255-6e4a-460c-b495-8569f1e75549)

**Comment by Honzackcz** [comment] 2024-01-15 05:32
For my heart rate, I use int in VRC parameters to receive and sync the value, and then in FX controller I have parameter with the same name but it's float. With C# parameter type mismatch causing to natively convert the int (0 - 255) to float (0.0 - 255.0) which is better to work with in animations.
Hope this might help you.

You can find more about parameter mismatch here
https://notes.sleightly.dev/parameter-mismatching/

**Comment by ChilloutCharles** [comment] 2024-01-15 06:33
That is one fortuitous hack! Good tip.

**Comment by SenkyDragon** [comment] 2024-01-31 08:36
I'm actually surprised this works. The dropdown only shows float params, correct?

**Comment by SenkyDragon** [comment] 2024-02-01 20:13
I double checked just to confirm, and using an int as a speed multiplier definitely does not work. It's not available in the property dropdown, and even if you type it manually, changes in the int value are not properly reflected as modifiers to the speed value. Strangely, it does seem to have /some/ impact, but it's unpredictable and certainly not something that should be used by design. Going to close this as won't fix.

**Closed by SenkyDragon** 2024-02-01 20:13 UTC
